### PR TITLE
Bugfix/#110

### PR DESCRIPTION
**Pull request by pranjaltale16**
### Proposed changes in this pull request

Added Profile image option in user model.

### When should this PR be merged

This PR can be merged directly-

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ ] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [ ] ** Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [ ] ** Are all UI and API inputs run through forms or serializers?** 
- [ ] ** Are all external inputs validated and sanitized appropriately?**
- [ ] ** Does all branching logic have a default case?**
- [ ] ** Does this solution handle outliers and edge cases gracefully?**
- [ ] ** Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by pranjaltale16** [comment]
Hello,

## In this Pull Request 
  1. I have added `S3FileField` for image upload and thumbnail function in order to access its thumbnail.
  2. I have to add Image cropper for it. I tried to add [this](https://foliotek.github.io/Croppie/) and completely integrated it, but it is not saving its instance rather than saving the complete image so I have to look for some other alternative for it.
  3. Integrated Profile Image in 'navbar/header' and 'users permission page'.

## Things to look upon
  1. We can add [django-image-cropper](https://github.com/jonasundderwolf/django-image-cropping) but probably this has to be added in Django-buckets (please correct me I am not sure about it).
  2. How should I modify the test of `accounts`, Is it good to save the default image and provide it in tests?
  3. Is it okay to work on Documentation once the changes are done and PR is merged, or shall I start working on it now?  

Is there anything else to look upon?

**Comment by pranjaltale16** [comment]
Here are a few snaps of the pull.

screenshot from 2017-03-23 12-48-32
screenshot from 2017-03-23 12-49-00
screenshot from 2017-03-23 12-49-19

**Comment by clash99** [comment]
Hi @pranjaltale16 - I wanted to mention a small ui change too - Can we change "Select the file to upload" to "Select the file to use for your profile picture"?  I don't think this should be a required field.  Ideally we will have a set stock of default images that we can use as placeholders.

**Comment by pranjaltale16** [comment]
@oliverroick @clash99  Thanks for your feedback, 
1. I will make the changes corresponding to test, with respect to the additions 
Currently, I modified only one test in accounts. I will update all the tests for default profile image.
2. I have used the concept of `thumbnail` function but I have modified it for accounts in a different manner. For the case of `create_thumbnail` I will modify the function in resources so that one can easily use it in resources and accounts both.
3. Yes, we can Update the text for 'Choose file' and currently, it is not a required field if the user doesn't want to add any Profile picture it will show a default image like [this](https://cloud.githubusercontent.com/assets/15308785/24236302/5397d08e-0fc7-11e7-8986-fab529915165.png).

I will start working on the above mentioned points. Is there anything else to look Upon?

**Comment by oliverroick** [comment]
@pranjaltale16 I would suggest you address those points and then we'll take it form there.

**Comment by pranjaltale16** [comment]
@oliverroick, Sure I will do that.

**Comment by pranjaltale16** [comment]
Hello, 
  1. I resolved all the errors in pep8 and current tests. I need help in writing tests for file upload, is there any particular method that has to be followed in order to add tests related to `django-buckets file upload`? I am trying to follow [this](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/resources/tests/test_forms.py#L16) is it okay? Also, the main additions that I have done is in `forms.py` and `models.py` so I will add tests for both, is there anywhere else where I should add tests.
  2. I modified the [create_thumbnail](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/resources/models.py#L156) function such that it can be used in both the places, so is okay to modify this(everything is running perfectly).
  3. How should I deal with migrations, Could you please help me over this?

**Comment by oliverroick** [comment]
@pranjaltale16 

1. You don't need to add tests to django-buckets. I think the test example you have linked will be sufficient. 
2. It's ok to modify `create_thumbnail`; I can't say much about your solution because you haven't provided any code. Just update this PR whenever your solution is ready and we'll give suggestions in the next review. 
3. The migrations that I mentioned can be removed. Just delete the corresponding files in the directory `accounts/migrations`

**Comment by pranjaltale16** [comment]
@oliverroick 
  I will push the commits corresponding to `create_thumbnail` and `migrations` in a while.
  Also, will complete the tests for profile image taking reference of [this](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/resources/tests/test_forms.py#L16).

**Comment by oliverroick** [comment]
Hey @pranjaltale16, thanks for your work so far. 

Since there hasn't been any activity on this PR during the last two weeks, I'm going to close it for the time being. Please feel free to re-open time PR whenever you found time to continue your work.

**Pull request closed without merging**
