### PR TITLE
Issue 1092 fix

### PR DESCRIPTION
**Pull request by yoshi2095**
### Proposed changes in this pull request
Changed the order of divs (contact vs projects) on org pages - fix for issue 1092.

#### Functionality

- [x] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [x] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [x] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.

### CODE REVIEW

**Comment by clash99** [comment]
Hi @yoshi2095 - 

You only should need to adjust the css for responsive max-width: 991px.

The display: table and display: table-header-group properties are allowing the divs to stack opposite of their order in the html.  If you undo those styles, it should fix the issue.  I hope that helps!

Thanks,
Chandra

**Comment by yoshi2095** [comment]
Hi @oliverroick and @clash99, thanks for the review. I'll just commit the suggested changes. Thanks.

**Comment by yoshi2095** [comment]
Hi @oliverroick and @clash99, I have committed the new changes. Now, It's working just the way it should be. Everything is responsive, all the issues that @oliverroick highlighted in the previous commit are now solved and, the projects list appear before the contact information. Please review. Thanks.

**Comment by oliverroick** [comment]
@yoshi2095 I also just noticed you have been changing the CSS in `main.css` directly. `main.css` is a file which is auto-generated by SASS. You need to change the code in any of the `*.scss` files in that directory to make sure your changes persist.

**Comment by yoshi2095** [comment]
@oliverroick Hi oliver, thanks for the review. Sure, I will soon make the changes as suggested by you. But one thing, I can't reproduce the first case. i.e, this one: **In Chrome, the right-hand panel is still not visible**. In my tab, everything is visible just the right way:

screenshot-3

Although, I was able to produce the errors in other browsers, ill just fix them very soon.
Also, this time i'll make sure that I make the changes in .scss files and that they work in all the browsers. thanks again.

**Comment by yoshi2095** [comment]
hi @oliverroick, finally fixed the issue. I hope you wouldn't encounter any other bugs in this PR now. I have rechecked everything from my side, for every browser. I just need to make these changes in the scss file now, to make them persist. However, I looked up in the developer tools, but its just displaying the auto-generated main.css file. I tried changing the settings, but that didn't help. So, I just need to figure out exaclty which scss file do I need to make the changes in, and then I am done.

**Comment by yoshi2095** [comment]
hi @oliverroick, please confirm if its done or are there any other changes needed?

**Comment by yoshi2095** [comment]
@clash99 made the suggested changes. Please review. Thanks.

**Comment by yoshi2095** [comment]
Hi @clash99, Please confirm if its done or are there are any other changes needed. Thanks.

**Comment by clash99** [comment]
Looks good - thanks @yoshi2095

**Comment by amplifi** [comment]
@yoshi2095 Thanks for completing this PR! If you rebase your branch onto our master, I can merge your code.

**Comment by yoshi2095** [comment]
@amplifi done :)

**Pull request merged**
