### PR TITLE
Remove broken django.contrib.auth url endpoints

### PR DESCRIPTION
**Pull request by alukach**
### Proposed changes in this pull request

When working on #1332, I noticed that there were a number of URLs that simply raised errors (no representative template files for the different views exist).  These were all from `django.contrib.auth.urls`.  Please note that I did not check all existing URL endpoints, I simply noticed that all of these endpoints failed as I was looking for the used login and password reset endpoints.  There may be other broken endpoints from different packages.

[`/login/`](https://demo.cadasta.org/login/)
[`/logout/`](https://demo.cadasta.org/logout/)
[`/password_change/`](https://demo.cadasta.org/password_change/)
[`/password_change/done/`](https://demo.cadasta.org/password_change/done/)
[`/password_reset/`](https://demo.cadasta.org/password_reset/)
[`/password_reset/done/`](https://demo.cadasta.org/password_reset/done/)
[`/reset/<uidb64>/<token>/`](https://demo.cadasta.org/reset/<uidb64>/<token>/)
[`/reset/done/`](https://demo.cadasta.org/reset/done/)

These were discovered by running the `./manage.py show_urls` command provided by [Django Extensions](https://github.com/django-extensions/django-extensions), which I would recommend adding to `config/settings/dev_debug.py` (not sure if that can be used in this PR or in another as it is not really part of the bug fix).

### When should this PR be merged

No restrictions.

### Risks

I don't believe that there are any risks as all of these views throw a `500` error. At worst, removing them will return a user a `404` instead.

### Follow up actions

None

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ ] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [ ] ** Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [ ] ** Are all UI and API inputs run through forms or serializers?** 
- [ ] ** Are all external inputs validated and sanitized appropriately?**
- [ ] ** Does all branching logic have a default case?**
- [ ] ** Does this solution handle outliers and edge cases gracefully?**
- [ ] ** Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by alukach** [comment]
As an aside, I don't know how kosher it is to just fix a small bug that is observed rather than go through the Issues and sprint planning process. Can anyone please comment on this detail?

**Comment by oliverroick** [comment]
> As an aside, I don't know how kosher it is to just fix a small bug that is observed rather than go through the Issues and sprint planning process. Can anyone please comment on this detail?

I think, it's ok to just fix such issues if it's a quick fix. We're not a German administrative office where you need to get a form signed by three people to do something ;)

**Comment by alukach** [comment]
> I think, it's ok to just fix such issues if it's a quick fix. We're not a German administrative office where you need to get a form signed by three people to do something ;)

Glad to hear it. I see that it was [this commit](https://github.com/Cadasta/cadasta-platform/commit/5333cfbee8d8f0c8069f07632279e748b7ea6c1c#diff-0e3ebf40e4a360a4cfbdb78550872272R37) that added the line. Do you see any reasons with removing the entry?

**Comment by oliverroick** [comment]
Should be ok to remove the entry. It's probably just in there because I've lazy and just copied this from some tutorial.

**Pull request merged**
