### PR TITLE
Include cadasta app in Python path

### PR DESCRIPTION
**Pull request by seav**
### Proposed changes in this pull request
This PR allows functional tests to run even when Celery is installed. It was previously noted that when Celery is installed, the functional tests would not run properly (we encounter the `django.core.exceptions.ImproperlyConfigured` exception).

So instead of trying to disable Django when running functional tests (by unsetting the `DJANGO_SETTINGS_MODULE` environment variable before invoking Pytest), we make the Cadasta Django app findable by adding `/vagrant/cadasta` or `{toxinidir}/cadasta` into the Python path. Allowing Django to be loaded should be harmless because it is not used by the functional tests anyway.

### When should this PR be merged
Before the Async branch is merged.

### Risks
None foreseen.

### Follow-up actions
None. (But rebase the Async branch onto master when this PR is merged.)

#### General

**Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 

- [ ] Review 1
- [ ] Review 2

**Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 

- [ ] Review 1
- [ ] Review 2

**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

- [ ] Review 1
- [ ] Review 2

#### Functionality

**Are all requirements met?** Compare implemented functionality with the requirements specification.

- [ ] Review 1
- [ ] Review 2

**Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

- [ ] Review 1
- [ ] Review 2

#### Code

**Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.

- [ ] Review 1
- [ ] Review 2

**Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 

- [ ] Review 1
- [ ] Review 2

**Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

- [ ] Review 1
- [ ] Review 2

**Is the code documented sufficiently?** Large and complex classes, functions or methods must be annotated with comments following our [code-style guidelines](https://devwiki.corp.cadasta.org/Contributing%20Style%20Guide#documentation-and-comments).

- [ ] Review 1
- [ ] Review 2

**Has the scalability of this change been evaluated?**

- [ ] Review 1
- [ ] Review 2

**Is there a maintenance plan in place?**

- [ ] Review 1
- [ ] Review 2

#### Tests

**Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 

- [ ] Review 1
- [ ] Review 2

**If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.

- [ ] Review 1
- [ ] Review 2

**If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

- [ ] Review 1
- [ ] Review 2

#### Security

**Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**

- [ ] Review 1
- [ ] Review 2

**Are all UI and API inputs run through forms or serializers?** 

- [ ] Review 1
- [ ] Review 2

**Are all external inputs validated and sanitized appropriately?**

- [ ] Review 1
- [ ] Review 2

**Does all branching logic have a default case?**

- [ ] Review 1
- [ ] Review 2

**Does this solution handle outliers and edge cases gracefully?**

- [ ] Review 1
- [ ] Review 2

**Are all external communications secured and restricted to SSL?**

- [ ] Review 1
- [ ] Review 2

#### Documentation

**Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).

- [ ] Review 1
- [ ] Review 2

**Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).

- [ ] Review 1
- [ ] Review 2

**Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki. 

- [ ] Review 1
- [ ] Review 2

### CODE REVIEW

**Comment by alukach** [comment]
Great work, thanks for looking into this!

I rebased my `feature/async` branch off of this and tests passed: https://travis-ci.org/Cadasta/cadasta-platform/builds/301461952

**Comment by seav** [comment]
> I rebased my `feature/async` branch off of this and tests passed

Actually, not yet. Functional tests are skipped for normal commits (and so the Travis job trivially passes). The tests are only run for PRs to the `master` branch. We will have to see when the Async PR has been rebased. (Or you can temporarily introduce the changes in this PR into your PR to see if the tests will indeed pass.)

**Comment by alukach** [comment]
@seav Hmmm... so the functional tests don't do anything unless a PR ins created that points to `master`?  If so, maybe we should have them exit much sooner, they still take 4 minutes (https://travis-ci.org/Cadasta/cadasta-platform/jobs/301461643)

**Comment by alukach** [comment]
Seems all but two tests passed... strange, will look into it tomorrow. @seav feel free to offer any insight.

https://travis-ci.org/Cadasta/cadasta-platform/jobs/301777034

**Comment by seav** [comment]
> so the functional tests don't do anything unless a PR is created that points to master? If so, maybe we should have them exit much sooner, they still take 4 minutes

That's correct. Most of those 4 minutes are overhead related to setting up the Travis VM. I think we should try out the conditional builds beta feature of Travis that was released last September:
- https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions
- https://docs.travis-ci.com/user/conditional-builds-stages-jobs/

> Seems all but two tests passed

Actually, only 1 test failed: "1 failed, 77 passed in 425.19 seconds". I think this test failure is another race condition that I have to investigate. This particular test fails intermittently from what I've seen so far.

**Comment by alukach** [comment]
@seav Okay, restarted builds and it passed, so looks like you're right. It had failed twice in a row before.

Definitely +1 to using the `if` statement in travis for conditional build.

**Pull request merged**
