### PR TITLE
Fixed #1148

### LINKED ISSUE #1148: Search: clicking on search panel should go to the top of the page?
This is a really low prio issue, just in case it could improve usability. 

Steps to reproduce: 
1. Execute a search query resulting in many results
2. Going to the end of the query list (where the pagination is)
3. Click on search icon on the left panel. 

Current behaviour: 

Nothing happens

Expected behaviour: 

I think if the user would be redirected to the top of the page (where the search box is), usability would be better. 

What do you think @clash99?

### PR DESCRIPTION
**Pull request by iharsh234**
### Proposed changes in this pull request

When user clicked search icon again it will take him to top of page with animation. Animate is added just for  good user experience. #1148

### CODE REVIEW

**Comment by iharsh234** [comment]
@seav  what about changing location from top of page to top of div blocks containing results?
`$('html, body').animate({scrollTop:$('#results').position().top}, 'fast');
 $('#results').focus();`
If you think this to be more useful i would update PR with this one.

**Comment by seav** [comment]
Hi @iharsh234, as mentioned in the bug report, "I think if the user would be redirected to the top of the page (where the search box is), usability would be better." Your existing code, or your proposed update does not really address this. Also take note that on larger screens, the `html` and `body` elements are already scrolled to the top so your code will not work. What you want is to scroll the `main` element instead.

**Comment by seav** [comment]
Hi @iharsh234, are you still planning to work on this PR?

**Comment by iharsh234** [comment]
@seav , yeah sure was little busy with university mid sem exams. will do this by tomorrow. Sorry for being late.

**Comment by iharsh234** [comment]
@seav  , i had tried some div blocks like 'search results' and 'tbody' but most of it remains at same place (position before and after scrolling down to pagination ) even after scrolling , hence scrollTop doesn't seems to be working , Can you please guide me a bit?.

**Comment by linzjax** [comment]
@iharsh234 So you're on the right track with `animate({scrollTop:...})`, but tbody and search results are all contained inside of another element that has an overflow CSS property. Try and find that parent element

**Comment by iharsh234** [comment]
@linzjax , i think i got it working , is it `content-single` ?

**Comment by linzjax** [comment]
@iharsh234   👏 One more suggestion: I would look for something more concrete than the URL to anchor the action to. This side panel has a class that changes depending on the page, maybe hook it up to that?

**Comment by iharsh234** [comment]
```
 $( '.search').find('.search').click(function(){ 
	$('.content-single').animate({ scrollTop: 0 }, 'fast');
  });
```  
@linzjax  is it good?

**Comment by seav** [comment]
Hi @iharsh234, this is okay. You just need to rebase your branch onto master and then we'll be good to go.

**Pull request merged**
