### PR TITLE
Changes to PR template

### PR DESCRIPTION
**Pull request by oliverroick**
### Proposed changes in this pull request

- New checklist items for scalability and maintenance
- Adds two checkboxes per checklist item

### When should this PR be merged

When reviewed

### Risks

None

### Follow-up actions

None

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ ] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [ ] **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [ ] **Are all UI and API inputs run through forms or serializers?** 
- [ ] **Are all external inputs validated and sanitized appropriately?**
- [ ] **Does all branching logic have a default case?**
- [ ] **Does this solution handle outliers and edge cases gracefully?**
- [ ] **Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by oliverroick** [comment]
@seav 

> As an example, in the last section, we have checklist items asking if the docs have been updated. But it doesn't make sense to update the docs before the functionality introduced by the PR has been pushed to production. It would be better if the checklist items instead state if a GitHub issue or a PR has been submitted to the appropriate docs repository.

I agree, but we need to clarify with the programs team what process they would like us to follow. We should talk to @bethschechter and move this to a separate PR.

As for other items in this list that you think might need work, feel free to propose any changes.

**Comment by dpalomino** [comment]
Thanks @oliverroick @seav 

>>As an example, in the last section, we have checklist items asking if the docs have been updated. But it doesn't make sense to update the docs before the functionality introduced by the PR has been pushed to production. It would be better if the checklist items instead state if a GitHub issue or a PR has been submitted to the appropriate docs repository.

>I agree, but we need to clarify with the programs team what process they would like us to follow. We should talk to @bethschechter and move this to a separate PR.

@bethschechter and I usually meet once per sprint (after the release) to review all the changes that are needed in the UI documentation, depending on the PRs that have been merged. I think it can be useful to include the "Need UI (or API) documentation" checkbox so it's easier to identify the changes, but I'm usually reviewing all the PRs included in the release to see the changes that we need in the UI documentation, so whatever you prefer.

**Comment by bethschechter** [comment]
Hey all, 

I am glad to see documentation added to the checklist, and I also agree that it's better to update the documentation after the changes have been moved to production (in the event that change requires some kind of documentation).

@dpalomino is right that we check in after sprints...though I wonder, what if your production checklist is for you to make an issue on `cadasta-docs` for me to address as soon as possible? that way you can still push to production and the features that need to be documented are noted.

**Comment by amplifi** [comment]
The documentation items in the checklist refers to multiple types of documentation that may arise from a PR, whether that's user-facing vs internal, technical vs non-technical, architectural, financial, etc. It's intentionally broad due to the varying nature of PRs, and there are types of documentation that we should be updating as we go rather than commencing update after deployment to production (such as reusable components, which should have documentation prepared before we merge into master).

The purpose of the checklist is for the reviewer to assess the completeness and readiness of the PR, to make sure the reviewer is considering each of these facets. That means if the reviewer checks with the author and confirms that a corresponding issue has been created on the docs repo, or that the feature specification has been updated to reflect changes to development, that should be sufficient.

As noted, the discussion should be moved to a new GitHub Issue; this PR doesn't involve any changes to the documentation items on the checklist.

**Pull request merged**
