### PR TITLE
DISREGARD THIS PR

### PR DESCRIPTION
**Pull request by alukach**
Doing some tests on Travis' Functional Tests.

### CODE REVIEW

**Comment by seav** [comment]
@alukach: By the way, if you think we need to update HTML IDs and class names (for example `DataTables_Table_0` is certainly no longer an appropriate ID because we are no longer using DataTables for some tables), feel free to do so and we can update the functional tests to match.

**Comment by alukach** [comment]
@seav Agreed, if you look at the last commit you can see that I put those IDs and class names in while I was doing a mad-dash to try to get tests to pass.  My rationale up to this point has been "just make it work" and then we can refine the code to fit best practice (for example, this PR has the compiled JSX in it, which is something that we should remove before we merge into `master`.

**Comment by alukach** [comment]
@oliverroick From @seav's comments in #1940, I've been able to get all but 1 test passing in this branch.  The last commit was an attempt to make that test pass however I was unsuccessful. I'm going to leave it in your hands from here on out.

**Comment by seav** [comment]
Okay, I was able to run a debug test on Travis. You can find the log file here: https://travis-ci.org/Cadasta/cadasta-platform/jobs/330696952

Based on the [following lines of output](https://travis-ci.org/Cadasta/cadasta-platform/jobs/330696952#L1076-L1082) there is a compilation error that is happening:

```
<div id="summary">
  <h1>CompileError at /dashboard/</h1>
  <pre class="exception_value">Error: File to import not found or unreadable: bootstrap-sass/assets/stylesheets/bootstrap/variables.
       Parent style sheet: /home/travis/build/Cadasta/cadasta-platform/cadasta/core/static/css/_variables.scss
        on line 74 of core/static/css/_variables.scss
&gt;&gt; @import &quot;bootstrap-sass/assets/stylesheets/bootstrap/variables&quot;;
   ^
```

So the website is not loading properly on Travis for the `optimization/react-table-views` branch.

**Comment by oliverroick** [comment]
@alukach I fixed the last functional test. You were almost there with your last commit, you just needed to make sure that the message is returned (you just returned an empty string).

I also had to update `cadasta-test` and add a wait to `test_search_that_results_in_no_party_works` to account for the time it takes to query the API. The functional tests for this branch are now running against `cadasta-test@pagination`, so we should merge PR https://github.com/Cadasta/cadasta-test/pull/65 and create a new release before we merge this PR.

**Comment by alukach** [comment]
This PR has served it's purpose, #1940 is now passing.

**Pull request closed without merging**
