### PR TITLE
Fix/#1267 Add detail table to resource-detail page.

### LINKED ISSUE #1267: Identify resource file size
For our users with slower connections, it would be good for them to know the file sizes of our resources before they choose to download them.  Can we add this next to the file names and the download buttons?

### PR DESCRIPTION
**Pull request by khantaalaman**
### Proposed changes in this pull request

Fix #1267 

- A resource detail table was added to let user know various aspects of the resource like size, dimensions (for images), file type etc.

### When should this PR be merged

After review

### Risks

- None

### Follow-up actions

[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]

- None

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ ] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [ ] **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [ ] **Are all UI and API inputs run through forms or serializers?** 
- [ ] **Are all external inputs validated and sanitized appropriately?**
- [ ] **Does all branching logic have a default case?**
- [ ] **Does this solution handle outliers and edge cases gracefully?**
- [ ] **Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by khantaalaman** [comment]
Supporting screenshot:

screen shot 2017-03-28 at 12 31 00 pm

Thanks!

**Comment by seav** [comment]
Hi @khantaalaman. Thanks for working on this issue. Unfortunately, your solution will not work when the code is deployed to production. In the production website, all resources are uploaded from the user's computer straight to Amazon S3. The Cadasta website does not see these files at all (except for non-TIFF images where the image file is downloaded from S3 to the website to generate thumbnails).

We are currently planning to fix file/resource uploads and downloads (see #490) and we want to get that fix merged first before we can tackle file information items such as file sizes and image dimensions.

**Comment by khantaalaman** [comment]
Okay @seav. It did come to my mind while using file path as used in the solution. Anyways, I'll continue with this as soon as aforementioned issue is resolved.

Thanks!

**Comment by khantaalaman** [comment]
By the @seav , do you think the approach to solve the issue is good enough to include this PR in my GSoC proposal?

**Comment by seav** [comment]
Assuming we will not be fixing #490 soon, your approach is not adequate. First of all, the PR has failed the Travis CI build. Second, files need to be copied from S3 to the website in order get file statistics and details: I would need to see something like `<resource_instance>.file.open()` somewhere in the code for it to work in the dev VM or in production.

**Comment by khantaalaman** [comment]
Okay @seav. Thanks a lot for your inputs. I will try to work upon it and improve this soon.

Thanks!

**Comment by amplifi** [comment]
The method suggested is incorrect. Resource files should never be copied from S3 to local server disk to obtain file metadata; it's an extremely inefficient and costly operation for this task. S3 makes file metadata, including the content size, available via API query. See: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html

Additionally, obtaining the file size of a resource from source every time a page is displayed is wasteful and won't scale. The file size is static, so we should be obtaining the file size once and storing it to db for later access. This will be handled as part of the async I/O work in #490, if not implemented here.

**Comment by oliverroick** [comment]
PR #1390 adds the basic for the resource details table, the complicated bits should be integrated into the work for #490. Going to close this PR now, thanks for your work @khantaalaman.

**Pull request closed without merging**
