### PR TITLE
BugFix #1745, case insensitive org/project name

### PR DESCRIPTION
**Pull request by valaparthvi**
### Proposed changes in this pull request

1. Make changes to `OrganizationForm` , `ProjectAddDetails` and `ProjectEditDetails` in `organization/forms.py`.
Use `name__iexact` instead of `name` when filtering out org/project. `name__iexact` is used for case-insensitive exact match, check [here](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#iexact).
Add an explicit uniqueness validation in `OrganizationForm`.
**Tests**
   - `OrganizationTest`: test_duplicate_name_error_case_insensitive
   - `ProjectAddDetailsTest`: test_add_new_project_with_duplicate_name_case_insensitive
   - `ProjectEditDetailsTest`: test_update_project_with_duplicate_name_case_insensitive

2. Make changes to `ProjectSerializer` and `OrganizationSerializer`.
Use `name__iexact` instead of `name` when filtering out org/project. `name__iexact` is used for the case-insensitive exact match.
Add an explicit uniqueness validation in `OrganizationSerializer`.
**Tests**
   - `OrganizationSerializerTest`: test_duplicate_organization_name_case_insensitive
   - `OrganizationSerializerTest`: test_update_with_duplicate_organization_name_case_insensitive
   - `ProjectSerializerTest`: test_duplicate_project_name_case_insensitive
   - `ProjectSerializerTest`: test_update_with_duplicate_project_name_case_insensitive

3. PEP8 auto formatting might have added some extra lines and spaces here and there.

### When should this PR be merged

- As soon as it's approved

### Risks

- Low

### Follow-up actions

- None

#### General

- **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.
  - [ ] Review 1
  - [ ] Review 2

#### Functionality

- **Are all requirements met?** Compare implemented functionality with the requirements specification.
  - [ ] Review 1
  - [ ] Review 2
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 
  - [ ] Review 1
  - [ ] Review 2

#### Code

- **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
  - [ ] Review 1
  - [ ] Review 2
- **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
  - [ ] Review 1
  - [ ] Review 2
- **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 
  - [ ] Review 1
  - [ ] Review 2
- **Is the code documented sufficiently?** Large and complex classes, functions or methods must be annotated with comments following our [code-style guidelines](https://devwiki.corp.cadasta.org/Contributing%20Style%20Guide#documentation-and-comments).
  - [ ] Review 1
  - [ ] Review 2
- **Has the scalability of this change been evaluated?**
  - [ ] Review 1
  - [ ] Review 2
- **Is there a maintenance plan in place?**
  - [ ] Review 1
  - [ ] Review 2

#### Tests

- **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
  - [ ] Review 1
  - [ ] Review 2
- **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
  - [ ] Review 1
  - [ ] Review 2
- **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?
  - [ ] Review 1
  - [ ] Review 2

#### Security

- **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
  - [ ] Review 1
  - [ ] Review 2
- **Are all UI and API inputs run through forms or serializers?** 
  - [ ] Review 1
  - [ ] Review 2
- **Are all external inputs validated and sanitized appropriately?**
  - [ ] Review 1
  - [ ] Review 2
- **Does all branching logic have a default case?**
  - [ ] Review 1
  - [ ] Review 2
- **Does this solution handle outliers and edge cases gracefully?**
  - [ ] Review 1
  - [ ] Review 2
- **Are all external communications secured and restricted to SSL?**
  - [ ] Review 1
  - [ ] Review 2

#### Documentation

- **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki. 
  - [ ] Review 1
  - [ ] Review 2

### CODE REVIEW

**Comment by valaparthvi** [comment]
> I recommend we modify the project name to require global uniqueness.

I am not sure I understand what you mean. Can you elaborate or give an example?

**Comment by amplifi** [comment]
@valaparthvi Sure :) The code as-is checks to make sure there is no other project with the same case-insensitive name in the same organization. So it's checking for project name uniqueness within an organization, rather than checking to make sure there's no other project with the same name existing in any organization (global uniqueness). If there's an existing org named "Cadasta" and a project named "Test", I could make a new org named "Cadatsa" with a project also named "Test" and that would pass validation.

**Comment by valaparthvi** [comment]
Oh okay, thanks, that makes sense now. I'll make the required changes to make sure that the project name is globally unique.

**Comment by valaparthvi** [comment]
Hey @amplifi, I have made the required changes. Project names will now be globally unique and I also modified the message "_Project with this name already exists in this organization_" to simply "_Project with this name already exists_" because that makes more sense.

**Pull request merged**
