### PR TITLE
Fixing Order permission roles according to level of permissions in se…

### PR DESCRIPTION
**Pull request by kavindya89**
### Proposed changes in this pull request

- https://github.com/Cadasta/cadasta-platform/issues/650
- Fixing Order permission roles according to level of permissions in select dropdown

### When** should this PR be merge
No Precondtions

### Risks
No Potential Risks

### CODE REVIEW

**Comment by ian-ross** [comment]
@kavindya89 I expect the tests are going to fail.  You need to fix those too.

**Comment by ian-ross** [comment]
You should always run tests locally before pushing to GitHub.  It's much quicker, because you don't need to wait for Travis to run the tests, and you can find the failing test and run it in isolation.

**Comment by kavindya89** [comment]
Oh sorry @ian-ross it was a basic mistake :(. I will do it.

**Comment by kavindya89** [comment]
@ian-ross done :+1:

**Comment by ian-ross** [comment]
@kavindya89 OK, that looks fine now.  I'll merge it tomorrow.  We're doing a release today, so we're in a code freeze now.

**Comment by kavindya89** [comment]
@ian-ross thank you!

**Comment by ian-ross** [comment]
I've pulled this into the repo as a branch so I could rebase it and made a new PR (#708) which I'll merge.

**Pull request closed without merging**
