### PR TITLE
Log and pass on TooBig errors from Memcached (fixes #1579)

### LINKED ISSUE #1579: Getting a platform error when accessing to a location
I've only been able to reproduce this issue in [this project](https://platform.cadasta.org/organizations/landesa/projects/telangana-survey) in platform. 

### Steps to reproduce the error

1. Go to this project and try to open any of the locations
2. You get a 500 error. 

Error log [here](https://cadasta.slack.com/files/slackbot/F5T1ZAFAS/uuj7q3u93qakbx9d7wyhq4ay). 

I've tried with a some projects both in staging and production and I've been not able to reproduce it.

### PR DESCRIPTION
**Pull request by alukach**
### Proposed changes in this pull request

#1579 occurs due to the abundance of `Attribute` instances being put into the cache as pickled Python objects. This PR addresses the issues around the cache throwing exceptions when a key value is greater than the cache's max-permitted size (currently set at 1MB).

This PR creates a new cache backend class. It inherits from our currently used (in production) backend, `django.core.cache.backends.memcached.PyLibMCCache`, however this backend catches any `pylibmc.TooBig` exceptions and logs them rather than raising them.

`pylibmc` needed to be bumped in patch version as the `TooBig` exception did not exist previously 
(surprising that they call that a patch version change and not a minor version change).

The issue of _why_ the key values were so large is addressed in Cadasta/django-jsonattrs#20.

### When should this PR be merged

Soon.

### Risks

To ensure that these errors don't go unnoticed, I've added the `core` module to the Production `LOGGERS` setting.  This may cause OpBeat to be a become a bit noisier, however I felt this was a better option than allowing caching issues to go unchecked.

The solution was done in a bit of a grandiose fashion, using metaclasses. If that leaves a bad taste in anyones mouth, it can be swapped out for a more standard subclass of the `django.core.cache.backends.memcached.PyLibMCCache` and overriding each method.

### Follow-up actions

None to think of.

#### General

- **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.
  - [ ] Review 1
  - [ ] Review 2

#### Functionality

- **Are all requirements met?** Compare implemented functionality with the requirements specification.
  - [ ] Review 1
  - [ ] Review 2
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 
  - [ ] Review 1
  - [ ] Review 2

#### Code

- **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
  - [ ] Review 1
  - [ ] Review 2
- **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
  - [ ] Review 1
  - [ ] Review 2
- **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 
  - [ ] Review 1
  - [ ] Review 2
- **Is the code documented sufficiently?** Large and complex classes, functions or methods must be annotated with comments following our [code-style guidelines](https://devwiki.corp.cadasta.org/Contributing%20Style%20Guide#documentation-and-comments).
  - [ ] Review 1
  - [ ] Review 2
- **Has the scalability of this change been evaluated?**
  - [ ] Review 1
  - [ ] Review 2
- **Is there a maintenance plan in place?**
  - [ ] Review 1
  - [ ] Review 2

#### Tests

- **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
  - [ ] Review 1
  - [ ] Review 2
- **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
  - [ ] Review 1
  - [ ] Review 2
- **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?
  - [ ] Review 1
  - [ ] Review 2

#### Security

- **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
  - [ ] Review 1
  - [ ] Review 2
- **Are all UI and API inputs run through forms or serializers?** 
  - [ ] Review 1
  - [ ] Review 2
- **Are all external inputs validated and sanitized appropriately?**
  - [ ] Review 1
  - [ ] Review 2
- **Does all branching logic have a default case?**
  - [ ] Review 1
  - [ ] Review 2
- **Does this solution handle outliers and edge cases gracefully?**
  - [ ] Review 1
  - [ ] Review 2
- **Are all external communications secured and restricted to SSL?**
  - [ ] Review 1
  - [ ] Review 2

#### Documentation

- **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki. 
  - [ ] Review 1
  - [ ] Review 2

### CODE REVIEW

**Comment by alukach** [comment]
@oliverroick Yes, I think that would be a good call.

However, before we do that, I notice there's a bit of cleanup in the docstring of the metaclass and I could write a quick test for the affirmative of "does the metaclass still allow errors to occur in non-mocked classes".

Also, can I get a quick verbal acknowledgment that we don't think there's an issue adding a logger to the `core` module in production? I don't want OpBeat to go crazy.

**Comment by amplifi** [comment]
> Also, can I get a quick verbal acknowledgment that we don't think there's an issue adding a logger to the core module in production? I don't want OpBeat to go crazy.

Good to add the logger. OpBeat batches like errors, and if it's chucking errors we should know about them anyway. Can always pare back if there's any issue.

**Comment by alukach** [comment]
Alright, I think this is now good to go. I've updated the requirements to use the most up-to-date version of `django-jsonattrs` and expanded tests slightly.

**Comment by alukach** [comment]
Ah, right, we need to publish the new version of `django-jsonattrs` and then the build will pass without failure. @oliverroick, I'm assuming you have permissions for that?

**Pull request merged**
