### PR TITLE
Bugfix/#844 - remove the Reset Password link in Edit Profile

### PR DESCRIPTION
**Pull request by aakanshavatsa**
### Proposed changes in this pull request

UI change to remove the Reset Password option in Edit Profile page.

### When should this PR be merged

Whenever possible.

### CODE REVIEW

**Comment by oliverroick** [comment]
@clash99 This PR is related to #844, what's your opinion on this? Should we remove the reset password link form user account pages? I think, we should not, it doesn't do any harm to have it.

**Comment by clash99** [comment]
@oliverroick:  I agree.  This link allows users that are logged in but don't know their password to reset it.  Its the same as selecting "forgot password" link on the login page without having to logout.  I don't see any harm in keeping it.  

I can see us moving it or making some changes to it once we develop our "Account/ Profile" pages in the future.

**Comment by oliverroick** [comment]
Right, closing this then.

@aakanshavatsa Thanks for your contribution, we really appreciate the work you put in. We have decided not to accept your PR because we think having the link might be helpful to some people.

**Comment by aakanshavatsa** [comment]
Thanks @clash99 and @oliverroick. 

I will close the bug as well.

**Pull request closed without merging**
