### PR TITLE
Fixing https://github.com/Cadasta/cadasta-platform/issues/754

### PR DESCRIPTION
**Pull request by kavindya89**
### Proposed changes in this pull request

Fixing https://github.com/Cadasta/cadasta-platform/issues/754
Issue Description : Can't add a resource in a location uploading a file

-
-
-

### When should this PR be merged

No preconditions

-
-
-

### Risks

No Risks

-
-
-

### Follow up actions

No follow up actions

-
-
-

### CODE REVIEW

**Comment by seav** [comment]
I looked a bit at the bug cause and I saw that the behavior was correct before until `resources` was somehow renamed to `resource`. So this bug is actually a regression. The problem is that this change should have been detected by a test. So for this PR, I would recommend that a unit test be created to detect this bug and also to confirm that the bug has been fixed.

**Comment by kavindya89** [comment]
@seav Thanks for looking to the issue. I too had a look on existing tests. There is a test in https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/spatial/tests/test_views_default.py#L772-L777 which align with this case. But it's getting success. It should be due to have some full permissions? I'm further looking on adding test case for simulate this case

**Comment by kavindya89** [comment]
@seav Added a test case as well. Let me know if there is any changes to be done

**Comment by linzjax** [comment]
Hi @kavindya89, thanks for updating the PR! Looks like everything will be good to go after one final thing.

You'll see that GitHub says "This branch is out-of-date with the base branch". That means that there have been changes in the main Cadasta/cadasta-platform repository that you don't have in your PR branch. That means that there's no way to know if your work is compatible with what's already been done. What you need to do in this case is to make sure that you've added our repo as an upstream remote for your fork (GitHub usually tells you to do this when you create a fork), fetch the latest master from there, and then update your PR branch to incorporate the latest changes. (This is the point where working directly on master in your repo turns out to be a bad idea...) If you're working on a topic branch, you do this:

```
git checkout master  # This is your local master branch
git fetch upstream/master  # Get changes from Cadasta/cadasta-platform
git merge upstream/master  # This does a "fast-forward" merge
git checkout <topic-branch>  # Switch back to your topic branch
git rebase master  # Replay the changes you've made on top of the latest upstream master
git push --force  # Update your PR on GitHub
```

If there are conflicts between your work and what's been done in the main repo, after you do the rebase, you'll get merge conflicts that you need to fix.

**Comment by seav** [comment]
@kavindya89, yes, you are correct that `test_post_with_authorized_user` is the correct test that should have caught this bug and that this is because the user has full permissions.

But instead of assigning a new policy and creating a new test, I think it is simpler to just modify the `assign_policies` function to specify `spatial.resources.*` instead of `spatial.*.*`. When you do this, two existing tests now fail: `test_get_with_authorized_user` and `test_post_with_authorized_user`. And when the bug fix is applied, these two tests now pass. So the problem with the tests is that the policy permissions being applied is too broad such that the misspelling of "resources" as "resource" is never caught.

**Comment by kavindya89** [comment]
@linzjax @seav thank you for the inputs I will do the necessary changes.

**Comment by kavindya89** [comment]
@linzjax @seav made necessary changes. Let me know anything to be changed.

**Pull request merged**
