### PR TITLE
Fix for https://github.com/Cadasta/cadasta-platform/issues/737

### PR DESCRIPTION
**Pull request by manoramahp**
### Proposed changes in this pull request

Fix for https://github.com/Cadasta/cadasta-platform/issues/737
### When should this PR be merged

Whenever possible

### CODE REVIEW

**Comment by oliverroick** [comment]
The Travis build is failing because you didn't add any tests for the code you have added. From quickly looking over your additions, you need to add tests for:

- `OrganizationRoleField`
- `OrganizationRoleWidget`
- `EditOrganizationMemberForm`

**Comment by manoramahp** [comment]
@oliverroick Thanks for the guidance. I will add tests for the newly added code.

**Comment by oliverroick** [comment]
The build for your branch is still failing. Please make sure you run the tests locally before pushing to Github. You run all tests at once by running `tox` from `/vagrant` inside the development VM.

**Comment by manoramahp** [comment]
@oliverroick I've added the required tests. Please review and merge PR.

**Comment by linzjax** [comment]
Hi @manoramahp, this is looking good! I have the same rebase request that @oliverroick did with your #703 PR, repasted below:

----------------
I have one final request, before we can merge your PR. Could you please squash the 5 commits in your branch into one and then rebase onto the latest changes in master? That will make merging your changes a lot easier for us.

You'll see that GitHub says "This branch is out-of-date with the base branch". That means that there have been changes in the main Cadasta/cadasta-platform repository that you don't have in your PR branch. That means that there's no way to know if your work is compatible with what's already been done. What you need to do in this case is to make sure that you've added our repo as an upstream remote for your fork (GitHub usually tells you to do this when you create a fork), fetch the latest master from there, and then update your PR branch to incorporate the latest changes. (This is the point where working directly on master in your repo turns out to be a bad idea...) If you're working on a topic branch, you do this:

```
git checkout master  # This is your local master branch
git fetch upstream/master  # Get changes from Cadasta/cadasta-platform
git merge upstream/master  # This does a "fast-forward" merge
git checkout <topic-branch>  # Switch back to your topic branch
git rebase master  # Replay the changes you've made on top of the latest upstream master
git push --force  # Update your PR on GitHub
```

If there are conflicts between your work and what's been done in the main repo, after you do the rebase, you'll get merge conflicts that you need to fix.

**Comment by seav** [comment]
I've added some comments on the issue [here](https://github.com/Cadasta/cadasta-platform/issues/737#issuecomment-252139023).

**Comment by manoramahp** [comment]
@seav Let me give some time to incorporate the improvements mentioned in https://github.com/Cadasta/cadasta-platform/issues/737#issuecomment-252139023

**Pull request closed without merging**
