### PR TITLE
Async Exports

### LINKED ISSUE #1400: Asynchronous Exports
Based on [DR 0006: Asynchronous Import and Export](https://github.com/Cadasta/decision-records/blob/master/0006_asynchronous_import_and_export.md), this task is focused on refactoring the data export tooling to support asynchronous operations. 

Asynchronous tasks should be scheduled by placing messages into a queue (most likely hosted via SQS). Celery seems like a reasonable tool to enable this. All data exchange between the Cadasta Platform and async services should go through the Cadasta API. By building services against our API, it will put the API into the place of a first-class feature of our system and ensure that it is battle-tested. It would be beneficial to work any issues out of an API as soon as possible, as alterations to APIs become very difficult once third-parties began building tooling against the API.

## Goals 

Data imports / exports should:

1. Avoid tying-up web server resources with unreasonably large requests
1. Avoid request timeout failures for long data operations
1. Allow users to navigate away from Upload/Export views while data operations continue
Flows

## Tasks

- [x] Convert API list views to utilize pagination
  - **This is a breaking change. Any current API consumers will needed to be updated to work with pagination. [See @SteadyCadence and QGIS Plugin].**
  - _see #1425_
- [x] Implement custom limited-access token authentication
  - See [prototype](https://gist.github.com/alukach/a136b5c07d1b9d2bd8b36173ec53f656/)
  - _see [Cadasta/drf-tmp-scoped-token](/Cadasta/drf-tmp-scoped-token)_
- [x] Create model to store BackgroundJob
  - This includes CRUD API Endpoints for BackgroundJob model
  - Model should be compatible with Celery Result Backend
  - _see #1624_
- [x] Integrate Celery Result Backend to utilize BackgroundJob Model
  - Lots of ways to implement this, we may be able to use RPC backend or write our own (see celery/celery#1581)
  - _see #1624_
- [x] Abstract Celery configuration
  - _see [Cadasta/cadasta-workertoolbox](/Cadasta/cadasta-workertoolbox)_
- [x] Implement Circuit Breaker tooling for celery tooling in Cadasta Platform
  - _see celery/kombu#769_
  - _see #1830_
- [x] Break out Export tooling into separate worker. 
  - Worker should authenticate with the API via the temporary limited-access auth token
  - Worker should take advantage of custom Celery Result Backend
  - _see [Cadasta/cadasta-export-worker](/Cadasta/cadasta-export-worker)_
    - [x] Support XLS exports
    - [x] Support Resource bundling
    - [x] Support Shapefile exports
  - [x] Set up logging with OpBeat
- [x] Store related `content_type` and `content_object` on `BackgroundTask` models.
  - _Implementation idea:_ Encode this data as task metadata when scheduled from Cadasta Platform. `sync_task` process will then use that metadata to populate fields.
- [x] ~Create email worker to send task outcomes to users.~
  - ~_see [Cadasta/cadasta-msg-worker](/Cadasta/cadasta-msg-worker)_~
  - _Email notifications will not be completed in this feature. Users can check export statuses via the Project Dashboard._
- [x] Create zip management server
  - _see [Cadasta/ZipStream-Service](/Cadasta/ZipStream-Service)_

### PR DESCRIPTION
**Pull request by alukach**
### Proposed changes in this pull request
Closes #1400.

#### General

**Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 

- [ ] Review 1
- [ ] Review 2

**Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 

- [ ] Review 1
- [ ] Review 2

**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

- [ ] Review 1
- [ ] Review 2

#### Functionality

**Are all requirements met?** Compare implemented functionality with the requirements specification.

- [ ] Review 1
- [ ] Review 2

**Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

- [ ] Review 1
- [ ] Review 2

#### Code

**Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.

- [ ] Review 1
- [ ] Review 2

**Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 

- [ ] Review 1
- [ ] Review 2

**Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

- [ ] Review 1
- [ ] Review 2

**Is the code documented sufficiently?** Large and complex classes, functions or methods must be annotated with comments following our [code-style guidelines](https://devwiki.corp.cadasta.org/Contributing%20Style%20Guide#documentation-and-comments).

- [ ] Review 1
- [ ] Review 2

**Has the scalability of this change been evaluated?**

- [ ] Review 1
- [ ] Review 2

**Is there a maintenance plan in place?**

- [ ] Review 1
- [ ] Review 2

#### Tests

**Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 

- [ ] Review 1
- [ ] Review 2

**If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.

- [ ] Review 1
- [ ] Review 2

**If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

- [ ] Review 1
- [ ] Review 2

#### Security

**Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**

- [ ] Review 1
- [ ] Review 2

**Are all UI and API inputs run through forms or serializers?** 

- [ ] Review 1
- [ ] Review 2

**Are all external inputs validated and sanitized appropriately?**

- [ ] Review 1
- [ ] Review 2

**Does all branching logic have a default case?**

- [ ] Review 1
- [ ] Review 2

**Does this solution handle outliers and edge cases gracefully?**

- [ ] Review 1
- [ ] Review 2

**Are all external communications secured and restricted to SSL?**

- [ ] Review 1
- [ ] Review 2

#### Documentation

**Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).

- [ ] Review 1
- [ ] Review 2

**Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).

- [ ] Review 1
- [ ] Review 2

**Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki. 

- [ ] Review 1
- [ ] Review 2

### CODE REVIEW

**Comment by alukach** [comment]
@seav @oliverroick Hmmm... functional tests failing again. There is likely a misconfiguration for the travis settings.  There still feels like a lack of transparency for _why_ the functional tests fail.  How do you feel about this idea: We put logging config in the travis settings to dump errors to a file, and then if the tests fail we `cat` the file on travis-ci.  This way, we can see what was going on server-side.

I could try to roll that into this branch, what do you two think?  Any better ideas?

**Comment by seav** [comment]
This is already a known issue. Functional tests and

**Comment by seav** [comment]
This is a already a known issue for the failure in this PR. Functional tests and celery don't mix. We still don't have a good solution for this one.

**Comment by seav** [comment]
@alukach: Remember that you tried running the functional tests in your local VM once and encountered the errors now showing on Travis in this PR? But you were able to successfully run the tests once you provisioned a new VM? In that new VM, celery isn't installed yet.

**Comment by alukach** [comment]
@seav Ah, right, I totally forgot that detail. Do you recall what the issue is? We will likely need a resolution before we can merge this. I'll see if I can figure out a solution.

**Comment by alukach** [comment]
@seav I feel like you and I chatted about the cause and potential fix for the build failures. B do you remember what those were?

**Comment by alukach** [comment]
@seav Okay, thanks for your comments over chat, looks like the failures were entirely due to some small mistakes in the code.  All good now.

**Pull request merged**
