### PR TITLE
Adds more allowed mime types

### LINKED ISSUE #1135: Resources: Support more MIME types
Updating the whole list of file types to be supported: 

Just drafting a list here for discussion:

Audio: 
- .mp3 (supported)
- .m4a (supported, but not listed)
- .mpa
- .ogg
- .wav
- .wma

Spreadsheet like: 
- .csv (supported)
- .xlsx (supported but not listed)
- .xls 
- .ods

Documents: 
- .docx (supported)
- .doc (supported)
- .odt 
- .rtf
- .txt

Presentation: 
- .ppt
- .pptx
- .key
- .odp

Images: 
- .jpg (supported)
- .png (supported)
- . jpeg (supported but not listed) 
- .bmp
- .gif
- .ps
- .svg
- .tif
- .tiff

Videos: 
- .mp4 (supported)
- .3gp
- .avi
- .m4v
- .mkv
- .mov
- .mpg
- .mpeg
- .wmv

----

There are some partners interested being able to upload Open Office formats: 
- .odt
- .ods
- .odp

BTW, is there any reason why we don't want to allow uploading many other file types? (.ppt, .pptx, .zip, etc?)

If there isn't I could propose a list with the filetypes... wdyt?

Thoughts @wonderchook, @bjohare ?

### PR DESCRIPTION
**Pull request by oliverroick**
### Proposed changes in this pull request

- Fixes #1135: Adds more mime types to the list of accepted types. 
- Excludes SVG images from creating thumbnails because vector graphics are not support by Pillow. 
- New thumbnails for non-images are already on the production buckts.

### When should this PR be merged

When ready. 

### Risks

None

### Follow-up actions

None. 

#### General

- **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.
  - [ ] Review 1
  - [ ] Review 2

#### Functionality

- **Are all requirements met?** Compare implemented functionality with the requirements specification.
  - [ ] Review 1
  - [ ] Review 2
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 
  - [ ] Review 1
  - [ ] Review 2

#### Code

- **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
  - [ ] Review 1
  - [ ] Review 2
- **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
  - [ ] Review 1
  - [ ] Review 2
- **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 
  - [ ] Review 1
  - [ ] Review 2
- **Is the code documented sufficiently?** Large and complex classes, functions or methods must be annotated with comments following our [code-style guidelines](https://devwiki.corp.cadasta.org/Contributing%20Style%20Guide#documentation-and-comments).
  - [ ] Review 1
  - [ ] Review 2
- **Has the scalability of this change been evaluated?**
  - [ ] Review 1
  - [ ] Review 2
- **Is there a maintenance plan in place?**
  - [ ] Review 1
  - [ ] Review 2

#### Tests

- **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
  - [ ] Review 1
  - [ ] Review 2
- **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
  - [ ] Review 1
  - [ ] Review 2
- **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?
  - [ ] Review 1
  - [ ] Review 2

#### Security

- **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
  - [ ] Review 1
  - [ ] Review 2
- **Are all UI and API inputs run through forms or serializers?** 
  - [ ] Review 1
  - [ ] Review 2
- **Are all external inputs validated and sanitized appropriately?**
  - [ ] Review 1
  - [ ] Review 2
- **Does all branching logic have a default case?**
  - [ ] Review 1
  - [ ] Review 2
- **Does this solution handle outliers and edge cases gracefully?**
  - [ ] Review 1
  - [ ] Review 2
- **Are all external communications secured and restricted to SSL?**
  - [ ] Review 1
  - [ ] Review 2

#### Documentation

- **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki. 
  - [ ] Review 1
  - [ ] Review 2

### CODE REVIEW

**Comment by oliverroick** [comment]
> Do we need to add a file size check to django-buckets as per the conversation in the issue?

We could, but it should be a separate ticket.

> Is there a reason we can't generate thumbnails for tif images..

We can create the thumbnail for a TIF, but it's not being displayed in some browsers. Instead, you'll see a placeholder that looks like the image wasn't loaded. That's why we excluded it for the time being, so we show the TIF icon by default. One possible solution is to convert the TIF into a PNG and create the thumbnail from that PNG. I think it's best to hold this off for when we are working moving file processing to an async worker.

**Comment by bjohare** [comment]
@oliverroick sounds reasonable.

**Comment by amplifi** [comment]
I don't think we should expand our supported mime types without first implementing the file size limit, particularly when the new list includes a lot of large file formats (video, PowerPoint/Keynote/presentation, etc). Any large files we allow to be uploaded now, we'll have to support and serve for the life of the platform. S3 has a max upload of 5GB in a single PUT -- that's a scary default limit for our contexts.

**Comment by alukach** [comment]
@amplifi I agree that we should address file-size limits soon (I'm impartial about the ordering of features). Doesn't seem like too-lofty of a task either, a quick google search suggests that we could specify the [`content-length-range` as a Condition](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html#sigv4-PolicyConditions) when [generating the upload policy](https://github.com/Cadasta/django-buckets/blob/master/buckets/storage.py#L90-L93) and we should be golden.

**Comment by dpalomino** [comment]
> I don't think we should expand our supported mime types without first implementing the file size limit, particularly when the new list includes a lot of large file formats (video, PowerPoint/Keynote/presentation, etc). Any large files we allow to be uploaded now, we'll have to support and serve for the life of the platform. S3 has a max upload of 5GB in a single PUT -- that's a scary default limit for our contexts.

Thanks @amplifi. I agree with you that we will need to establish a file size limit, but I do not think that we should stop the support the additional mime types. We are currently quite limited in the resource types that we can handle and partners are requesting this.

**Comment by oliverroick** [comment]
Ok, I'll go ahead and implement this into django-buckets. I suggest to hold off this PR then until that's done.

**Comment by amplifi** [comment]
Thanks, @oliverroick. I'll wait on the django-buckets update to merge this one.

**Pull request merged**
