### PR TITLE
Single page map scaffolding view and html. Upgrade (kinda) to Leaflet1.0

### PR DESCRIPTION
**Pull request by linzjax**
__NOTE__: This is not being merged into master. Opening this PR as the first step towards SMAP. It's caused some oddities across the platform because of Leaflet 1.0, but those will be dealt with, so pardon the mess.

### Proposed changes in this pull request
- Addresses #1057 
- ProjectMap will serve as the main view for all project pages (found at `/organization/{org-slug}/projects/{project-slug}/map/` for now)
- Side panel can be displayed or hidden by switching between `detail-hidden` and `detail-display`. Currently doesn't display anything.
- Upgraded _just_ project_map.html to Leaflet 1.0. Since other pages will be absorbed by this one, I am putting off the full upgrade until the other views have been reworked.
    - Note: the other maps will have some odd ticks until then.
- Currently only standard tests for ProjectMapView. Will add more as more functionality is added.
- Removed L.Deflate temporarily. Running into leaflet 1.0 compatibility issues.

### When should this PR be merged
Whenever

### Risks
None (not being merged into master)

### Follow up actions
- Continue the epic SMAP journey
- Finish the full upgrade to Leaflet 1.0 for other pages that remain intact after SMAP is completed.

---
#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts. 

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by seav** [comment]
> How have you written the CSS for the right-hand panel? It looks like you did something funny there. I wouldn't change the size of the map. Rather overlay the right-hand panel over the map and slide this in and out by just changing the left property; so basically move it out of the viewport.

I wouldn't recommend putting something large on top of the map as opposed to resizing the map. This affects Leaflet centering features such as centering the map on a location, or zooming in and panning the map to show some geometry as big as possible. If you put the sidebar over the map, the said geometry might be partially covered. There are ways in Leaflet to specify some margin for these centering features, but this becomes really messy quickly with responsive designs.

**Comment by oliverroick** [comment]
Good point, then we shall not do overlays and stick to resizing the map then.

**Comment by linzjax** [comment]
1. Great, I'll start a new file and go from there.

2. Looking over basics of modularizing, and I'll post more questions as I get a better sense of what I'm doing.

3. I'll go ahead and switch those over.

4. So the CSS is pretty wonky for now. As @seav pointed out, I changed the width because half of the map was getting covered up. It's a problem I'm pushing off for now, but if the map starts smaller and expands, the width of the container adjusts, but the map itself does not. This leaves a gray bar behind where the side menu was. So I'm still looking into the best way to do that.

**Comment by linzjax** [comment]
Ok, functionality has been set up for overview/map views, and destroyed for every other page (I'll deal with that later).

**Pull request merged**
