### PR TITLE
Disable DataTables on project-add permissions view

### PR DESCRIPTION
**Pull request by alukach**
### Proposed changes in this pull request

@SteadyCadence was experiencing an issue where she was unable to proceed past the "Step 3: Assign Permissions to Members" view of the Project Creation Wizard.  She reported that this occurred in projects with many users. Upon investigation, it appears that this occurs when there are any non-admin members that don't appear on the first page of 10 users:

This is because of the fact that DataTables removes the form elements from the view when they are not in the viewable page.

My solution was the simplest thing I could think of: remove usage of DataTables on this view.  This should have almost no performance implications as all users are loaded even with DataTable's pagination. Thus, this should purely be a UX change.  I struggled to think of any tests that would verify this fix, and thus didn't add any.

### When should this PR be merged

Anytime

### Risks

Little

### Follow-up actions

None come to mind.

#### General

**Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 

- [ ] Review 1
- [ ] Review 2

**Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 

- [ ] Review 1
- [ ] Review 2

**Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

- [ ] Review 1
- [ ] Review 2

#### Functionality

**Are all requirements met?** Compare implemented functionality with the requirements specification.

- [ ] Review 1
- [ ] Review 2

**Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

- [ ] Review 1
- [ ] Review 2

#### Code

**Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.

- [ ] Review 1
- [ ] Review 2

**Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 

- [ ] Review 1
- [ ] Review 2

**Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

- [ ] Review 1
- [ ] Review 2

**Is the code documented sufficiently?** Large and complex classes, functions or methods must be annotated with comments following our [code-style guidelines](https://devwiki.corp.cadasta.org/Contributing%20Style%20Guide#documentation-and-comments).

- [ ] Review 1
- [ ] Review 2

**Has the scalability of this change been evaluated?**

- [ ] Review 1
- [ ] Review 2

**Is there a maintenance plan in place?**

- [ ] Review 1
- [ ] Review 2

#### Tests

**Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 

- [ ] Review 1
- [ ] Review 2

**If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.

- [ ] Review 1
- [ ] Review 2

**If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

- [ ] Review 1
- [ ] Review 2

#### Security

**Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**

- [ ] Review 1
- [ ] Review 2

**Are all UI and API inputs run through forms or serializers?** 

- [ ] Review 1
- [ ] Review 2

**Are all external inputs validated and sanitized appropriately?**

- [ ] Review 1
- [ ] Review 2

**Does all branching logic have a default case?**

- [ ] Review 1
- [ ] Review 2

**Does this solution handle outliers and edge cases gracefully?**

- [ ] Review 1
- [ ] Review 2

**Are all external communications secured and restricted to SSL?**

- [ ] Review 1
- [ ] Review 2

#### Documentation

**Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).

- [ ] Review 1
- [ ] Review 2

**Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).

- [ ] Review 1
- [ ] Review 2

**Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki. 

- [ ] Review 1
- [ ] Review 2

### CODE REVIEW

**Comment by seav** [comment]
We've had a similar issue with resources. See #507 for reference.

**Comment by alukach** [comment]
@seav ah, indeed the same issue, do you have opinions on this fix? Any downsides that I am missing?

**Comment by seav** [comment]
Well, I find it a bit curious that the call to `activateFormFieldsInDataTable()` is not working since it is supposed to avoid precisely this problem. See the [source code for this function](https://github.com/Cadasta/cadasta-platform/blob/a6170a73603bddbc12679c73ca0a390616ca3ed0/cadasta/core/static/js/dataTables.forms.js).

Anyway, I think it should be OK to disable DataTables for this table. I imagine that the number of members in an organization would not be too many that we **need** DataTables’ pagination/search/filter feature. For the resources table, we definitely need it.

**Comment by alukach** [comment]
@seav Ah, interesting, I wasn't aware of the purpose of `activateFormFieldsInDataTable()` (maybe I should look before I delete).  You are right that the function should resolve the issue, it was just improperly targeting the form with CSS.  Fixing the CSS selector resolved the issue!

**Comment by alukach** [comment]
@seav Maybe I should write a functional test to ensure this does not regress?  Will chat with you about best advice on getting started with that.

**Comment by seav** [comment]
> Maybe I should write a functional test to ensure this does not regress?

@alukach: I agree. The first step would be to create a test case describing the issue. This can be similar to the test case for the multi-page resources (ID #A26) in the [Functional Test Cases spreadsheet](https://docs.google.com/spreadsheets/d/175BL8m3gzdVb-kPOLaZOCx8TJKDXgNQ9BE9x_NnNFt0/edit#gid=208031085). After that, we can implement a functional test for this.

**Comment by alukach** [comment]
@seav Okay, add [Projects:C16](https://docs.google.com/spreadsheets/d/175BL8m3gzdVb-kPOLaZOCx8TJKDXgNQ9BE9x_NnNFt0/edit#gid=2123564341&range=29:29). Feel free to critique.

**Pull request merged**
