### PR TITLE
Fix #1045: Remove incorrect password validation error

### LINKED ISSUE #1045: Incorrect password validation error
### Steps to reproduce the error

Navigate to the account registration page at https://platform-staging.cadasta.org/account/signup/. Enter a username, password, confirm password and full name. Leave the email field blank. Click 'Register'. The email validation error is displayed correctly but an incorrect password validation error message is displayed: *'Your password cannot contain your email mailbox name.'* The passwords were generated by *LastPass* and don't contain any reference to an email mailbox.

password

### Actual behavior

An incorrect password validation error is displayed.

### Expected behavior

I wouldn't expect a password validation error when a blank email field is provided.

### PR DESCRIPTION
**Pull request by shailysangwan**
### Proposed changes in this pull request

- Modify email in password check and username in password check to check for email length and username length first. Only proceed with the checks if length is non zero

- Fix https://github.com/Cadasta/cadasta-platform/issues/1045

### When should this PR be merged

- First PR, I'm not sure of this

### Risks

- None foreseen

### Follow up actions

- Possibly update the test data to accommodate this incorrect validation error

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ ] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by shailysangwan** [comment]
I tried running the tests (to add more for this possible test case), but I ran into the following error:

`
    (env)vagrant@vagrant-ubuntu-trusty-64:/vagrant/cadasta/accounts/tests$ python test_forms.py 
    Traceback (most recent call last):
      File "test_forms.py", line 7, in <module>
        from django.contrib.messages.storage.fallback import FallbackStorage
      File "/opt/cadasta/env/lib/python3.5/site-packages/django/contrib/messages/storage/fallback.py", line 1, in <module>
        from django.contrib.messages.storage.base import BaseStorage
      File "/opt/cadasta/env/lib/python3.5/site-packages/django/contrib/messages/storage/base.py", line 7, in <module>
        LEVEL_TAGS = utils.get_level_tags()
      File "/opt/cadasta/env/lib/python3.5/site-packages/django/contrib/messages/utils.py", line 10, in get_level_tags
        level_tags.update(getattr(settings, 'MESSAGE_TAGS', {}))
      File "/opt/cadasta/env/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
        self._setup(name)
      File "/opt/cadasta/env/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
        self._wrapped = Settings(settings_module)
      File "/opt/cadasta/env/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
        mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/opt/cadasta/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: No module named 'config'

`

**Comment by wonderchook** [comment]
@shailysangwan are you meaning for this to be a pull request? If so please fill out the questions asked. If you don't know the answer you can say that.

**Comment by shailysangwan** [comment]
I don't quite understand what the checks in serializers.py are for, so I've made two separate commits for both the files for now.
Can you help me understand?

**Comment by wonderchook** [comment]
Can you come into gitter and I will see what i can do? https://gitter.im/Cadasta/cadasta

**Comment by manoramahp** [comment]
@oliverroick  I believe what is mentioned in this comment https://github.com/Cadasta/cadasta-platform/pull/675#issuecomment-246654188 is applicable to this PR as well.

**Pull request closed without merging**
