### PR TITLE
issue-1002-fixed

### PR DESCRIPTION
**Pull request by yoshi2095**
### Proposed changes in this pull request
Included the Search and Go-To-My-Location map controls in Project Overview and Map pages.

#### Functionality

- [x] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [x] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled.

### CODE REVIEW

**Comment by shailysangwan** [comment]
@yoshi2095 The checklist is meant for the reviewers to fill :)

**Comment by linzjax** [comment]
Hi @yoshi2095, your solution works and your PR looks good to go, but I have one final request before we can merge your PR. Could you please rebase onto the latest changes in master? That will make merging your changes a lot easier for us.

You'll see that GitHub says "This branch is out-of-date with the base branch". That means that there have been changes in the main `Cadasta/cadasta-platform` repository that you don't have in your PR branch. That means that there's no way to know if your work is compatible with what's already been done. What you need to do in this case is to make sure that you've added our repo as an upstream remote for your fork (GitHub usually tells you to do this when you create a fork), fetch the latest master from there, and then update your PR branch to incorporate the latest changes. If you're working on a topic branch, you do this:

```
git checkout master  # This is your local master branch
git fetch upstream/master  # Get changes from Cadasta/cadasta-platform
git merge upstream/master  # This does a "fast-forward" merge
git checkout <topic-branch>  # Switch back to your topic branch
git rebase master  # Replay the changes you've made on top of the latest upstream master
git push --force  # Update your PR on GitHub
```

If there are conflicts between your work and what's been done in the main repo, after you do the rebase you'll get merge conflicts that you need to fix.

**Comment by yoshi2095** [comment]
@linzjax done :+1:

**Comment by linzjax** [comment]
Hmmm... It looks like you're still 17 commits behind Cadasta's master branch. Is the cadasta repository set as your remote upstream? If you run: 
```
git remote -v
```
it'll return something that looks like this:
```
origin	    git@github.com:<your-username>/cadasta-platform.git (fetch)
upstream    git@github.com:Cadasta/cadasta-platform.git (fetch)
```
If you don't see `upstream   git@github.com:Cadasta/cadasta-platform.git (fetch)`, you'll need to set your upstream branch:
```
git remote add upstream git@github.com:Cadasta/cadasta-platform.git
```
Then try running the rebase steps again.

**Comment by yoshi2095** [comment]
@linzjax done :+1: . Earlier, I didn't have any public SSH keys for my account. That's why it wasn't merging the commits. I made one, and its all good now.

**Comment by linzjax** [comment]
@yoshi2095, thanks for your changes. This looks good. We will merge your contribution soon!

**Comment by yoshi2095** [comment]
@linzjax Thank you :)

**Pull request merged**
