### PR TITLE
Questionnaire choice labels

### LINKED ISSUE #478: Adding New Location - Drop Down Pulling from Name instead of Label
Using the generic Cadasta excel form, it seems the drop down lists are pulling from the "Field Name" as opposed to Field Label, which will cause confusion when doing data entry from the PC, particularly when the name isn't obvious.
error_excel_namelabel

error_label

### PR DESCRIPTION
**Pull request by ian-ross**
### Proposed changes in this pull request

- Fix #478.
- Bump `django-jsonattrs` version to a version supporting labels for choice fields.  This automatically makes dropdowns in attribute forms and attribute detail views use choice labels if they exist.
- Add question option ordering (to keep same order in dropdowns as in XLSForms).
- Migrations:
    * Schema: add `choice_labels` column for `django-jsonattrs` `Attribute` model (`django-jsonattrs/jsonattrs/migrations/0002_attribute_choice_labels.py`).
    * Data: copy over attribute choice labels from `QuestionOption` models to new `choice_labels` field `django-jsonattr` `Attribute` instances (`cadasta-platform/cadasta/questionnaires/migrations/0006_add_choice_labels.py`).
    * Schema: add `index` field to `QuestionOption` model, initially with `null=True` and a default value to populate existing instances (`cadasta-platform/cadasta/questionnaires/migrations/0007_add_question_option_index_field.py`).
    * Data: set appropriate index values for all existing `QuestionOption` instances (`cadasta-platform/cadasta/questionnaires/migrations/0008_populate_question_option_index_field.py`).
    * Schema: change `QuestionOption` `index` field to have `null=False` (`cadasta-platform/cadasta/questionnaires/migrations/0009_set_question_option_index_field_properties.py`).

The approach taken for setting up the `index` field in the `QuestionOption` model is the recommended approach for adding non-NULL fields to existing Django models (add the field with `null=True` in one migration, fix up the data values in a second migration, then set `null=False` in a third migration).

### When should this PR be merged

I'd be very happy if this could have a "dogpile" review.  In particular, I'd like @oliverroick, @bjohare and @linzjax to have a look at it to see if they can spot any possible problems with the migrations.  I'd also like to do some testing on staging with a mirror of the current production database.

### Risks

All the usual dangers associated with database migrations...

### Follow up actions

None.

### CODE REVIEW

**Comment by ian-ross** [comment]
You're right.  I'll fix that!

**Comment by ian-ross** [comment]
I've changed this, but I want to have a bit of a test on staging first before it's merged.  I'll let you know when I've done that.

**Comment by linzjax** [comment]
So it's working for adding locations, but not for tenure or parties:
screen shot 2016-09-28 at 10 55 30 am

screen shot 2016-09-28 at 10 55 58 am
screen shot 2016-09-28 at 10 56 04 am

**Comment by ian-ross** [comment]
Huh.  Let me look at that!

**Comment by ian-ross** [comment]
OK, I know what this is.  I'll fix it somehow.

**Pull request merged**
