### PR TITLE
Async: Configure DB and Cadasta Platform dev VM to support async workers

### PR DESCRIPTION
**Pull request by alukach**
### Proposed changes in this pull request

_NOTE: This PR works towards the goals of #1400_

Our asynchronous task consumers need to be able to access the Cadasta DB in order to record task results. This PR includes changes that ensure that:

1. The dev VM exposes its DB to the host machine. This is done by altering the Vagrantfile to port-forward Postgres' port (`5432`) to host machine (`5433`). This is helpful when running a worker on the host machine.
1. The results tables of the database are set up in accordance to the expectations of the Celery database result backend. This required renaming the sequence generated by Django to match the sequence expected by Celery.
1. A DB user is created via Ansible in both dev and production environments. This DB worker should only have access to Create, Read, and Update task results and to increment the sequences responsible for generating IDs of new TaskResults. This command runs every time a machine is provisioned or a codebase is deployed. Given that Ansible aims to be idempotent, no harm will come if the users/permissions are already present in the database.
1. The `uwsgi` process serving our application in production has awareness of the [`RESULT_DB_*`](https://github.com/Cadasta/cadasta-workertoolbox#result_db_user) settings. Currently, I've only set the `RESULT_DB_HOST` value, although we probably should set the others as well. I'm not really sure how this should be done and am looking for input.

To test, you can checkout the [export-worker](https://github.com/Cadasta/cadasta-export-worker) and process the message. Assuming that you have SQS access, you'll need to:
1. Reprovision your Vagrant VM (`vagrant provision`)
1. Schedule a task (`python -c "from app.celery import app; from cadasta.workertoolbox.setup import setup_app; setup_app(app); app.send_task('export.project')"`) (note that this will fail as the proper arguments are not provided. the failure should still be logged in the DB)
1. Run the worker `RESULT_DB_PORT=5433 S3_BUCKET=my_bucket ./startworker -l INFO`
1. Either run `SQS=1 ./manage.py sync_tasks` in your VagrantVM or check the `celery_taskmeta` table for results. The later is probably easier, as it does not require you to have SQS access on the Vagrant VM.

If you don't have SQS access, you can install RabbitMQ and use that. This will require you to override the [`broker_transport`](https://github.com/Cadasta/cadasta-workertoolbox#broker_transport) to something like `'amqp://myuser:mypassword@localhost:5672/myvhost'` when running both scheduling the task and running the worker. (actually, after writing this, I realize that we don't currently support overriding the [`broker_transport` variable](https://github.com/Cadasta/cadasta-workertoolbox/blob/master/cadasta/workertoolbox/conf.py#L14). This could be a quick change if need be)

If you want the tasks to actually succeed, you will also need to:
* run the [zipstream service](https://github.com/ZipStream).
* ensure the `ZIPSTREAM_URL` and `PLATFORM_URL` env variables are set if [the default values](https://github.com/Cadasta/cadasta-export-worker/blob/master/app/settings.py#L4-L7) are not correct for your setup.
* set the `S3_BUCKET` env variable to a bucket that you have permissions to access. This will be the bucket that will receive generated export files.

### When should this PR be merged

This PR is a requirement for #1400.

### Risks

There is a change to `tasks/migrations/0001_initial.py`, however being that this PR is pointed at `feature/async`, I believe that this is acceptable.

Questions:

* Do we manage security groups via any configuration management tooling? Currently, no work has been done to ensure that RDS permits access to the workers via its security groups
* How should I approach setting the other `RESULT_DB_*` config variables on the `uwsgi` server? @amplifi mentioned that the DB passwords are overwritten at deployment. I'm not really quite sure how this works, we would need access to that new value. I would imagine it would take place around [here](https://github.com/Cadasta/cadasta-platform/blob/async%2Fconfigure-db-access/deployment/scripts/deploy#L227-L236) however I'm not seeing it...

### Follow-up actions

See #1400 for followup tasks.

#### General

- **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.
  - [ ] Review 1
  - [ ] Review 2

#### Functionality

- **Are all requirements met?** Compare implemented functionality with the requirements specification.
  - [ ] Review 1
  - [ ] Review 2
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 
  - [ ] Review 1
  - [ ] Review 2

#### Code

- **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
  - [ ] Review 1
  - [ ] Review 2
- **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
  - [ ] Review 1
  - [ ] Review 2
- **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 
  - [ ] Review 1
  - [ ] Review 2
- **Is the code documented sufficiently?** Large and complex classes, functions or methods must be annotated with comments following our [code-style guidelines](https://devwiki.corp.cadasta.org/Contributing%20Style%20Guide#documentation-and-comments).
  - [ ] Review 1
  - [ ] Review 2
- **Has the scalability of this change been evaluated?**
  - [ ] Review 1
  - [ ] Review 2
- **Is there a maintenance plan in place?**
  - [ ] Review 1
  - [ ] Review 2

#### Tests

- **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
  - [ ] Review 1
  - [ ] Review 2
- **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
  - [ ] Review 1
  - [ ] Review 2
- **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?
  - [ ] Review 1
  - [ ] Review 2

#### Security

- **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
  - [ ] Review 1
  - [ ] Review 2
- **Are all UI and API inputs run through forms or serializers?** 
  - [ ] Review 1
  - [ ] Review 2
- **Are all external inputs validated and sanitized appropriately?**
  - [ ] Review 1
  - [ ] Review 2
- **Does all branching logic have a default case?**
  - [ ] Review 1
  - [ ] Review 2
- **Does this solution handle outliers and edge cases gracefully?**
  - [ ] Review 1
  - [ ] Review 2
- **Are all external communications secured and restricted to SSL?**
  - [ ] Review 1
  - [ ] Review 2

#### Documentation

- **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki. 
  - [ ] Review 1
  - [ ] Review 2

### CODE REVIEW

**Comment by amplifi** [comment]
@oliverroick `listen` for handlers was introduced in Ansible v2.2. If you're on the older version specified in the readme, this PR will require an upgrade. There shouldn't be any harm in upgrading to 2.2 and we can update the readme to reflect.

**Comment by oliverroick** [comment]
Thanks, @amplifi. 

Now I'm getting

```
RUNNING HANDLER [db/development : Configure worker table priviliges] ***********
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "relation \"public.celery_tasksetmeta\" does not exist\n"}
```

That table is not present in the database; I also can't find a migration for it.

**Comment by alukach** [comment]
@oliverroick The `celery_tasksetmeta` table is created by a Celery task consumer's DB backend. It is created automatically when a consumer first records a result if the table is not already present. The table itself is no longer used, as of [the 4.0 release](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html?highlight=%22TaskSet%22#taskset), I assume it's been left in for backwards-compatibility. 

No permissions need to be added for this table (being that it is unused).  I have removed those declarations from the Ansible handlers.

However, it is a bit strange that the worker is even able to create tables... I spent a few minutes attempting to revoke this permission (`REVOKE CREATE ON SCHEMA public FROM worker;`, `REVOKE CREATE ON DATABASE cadasta FROM worker;`) but came up empty handed.  Please advise whether it is acceptable or not for the worker user to have this permission. Any advice on how to revoke this permission would also be appreciated.

**Comment by alukach** [comment]
@amplifi Thanks for pointing out the version discrepancy. I've upped the version in the `README.rst`

**Comment by oliverroick** [comment]
Getting similar error now:

```
RUNNING HANDLER [db/development : Configure worker sequence priviliges] ********
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "relation \"public.task_id_sequence\" does not exist\n"}
	to retry, use: --limit @/Volumes/Work/dev/temp/cadasta-platform/provision/vagrant.retry
```

**Comment by alukach** [comment]
@oliverroick Hmm... My guess is that you have already run `tasks/migrations/0001` when you were QAing #1624. Could you please run `./manage migrate tasks zero` and then reprovision your VM?

**Comment by alukach** [comment]
@oliverroick Hmmm... I'm clueless as to why you would get that particular error. I ran it and got another error due to forgetting to remove reference to a sequence (which I've now removed). Assuming that `tasks/migrations/0001` runs, `task_id_sequence` should be present in the database, and the Ansible task from your error _should_ run after the migration, so 😕 .

Would you be willing to pull the last code and try just one more time?

**Pull request merged**
