### PR TITLE
Fix #1264: Add thumbnail preview to edit resources page.

### LINKED ISSUE #1264: Add thumbnail preview to edit resources page
Currently there isn't a thumbnail preview on the edit resources page.  Ideally we could use the same 128 X 128 on the resource detail page and add it to the resource edit page.

**Current page:**

screenshot 2017-03-09 16 56 17

**Proposed change:**

edit preview

### PR DESCRIPTION
**Pull request by khantaalaman**
### Proposed changes in this pull request

Fix #1264 

- Added thumbnail preview to edit resources page, like the one we already have on resource detail page.

### When should this PR be merged

[Please describe any preconditions that need to be addressed before we
can merge this pull request.]

No preconditions.

### Risks

[List any risks that could arise from merging your pull request.]

- None

### Follow up actions

[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]

- None

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ ] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by khantaalaman** [comment]
Supporting screenshot:

screenshot from 2017-03-10 04-50-49

@clash99 Please suggest improvements to this PR, if any.

Thanks! :)

**Comment by khantaalaman** [comment]
Hi @clash99 ,
I am extremely sorry for enormous delay with this. The PR has been updated. I am having 2 doubts before asking for the final review:
1. Upon removing a file and then uploading a new file, do we want to show new resource's thumbnail?
2. In the changes that I made, (Remove) is coming below file name. Also, file name is still blue and not black, as suggested in wireframe. These were looking fine to me and I had them as it is. Do you want me to make them as in wireframe? 

Current screenshot:

screenshot from 2017-03-26 21-14-10

**Comment by khantaalaman** [comment]
Ping @clash99

**Comment by amplifi** [comment]
Hi @khantaalaman, thanks for your work so far.

Since there hasn't been any activity on this PR in the last few weeks, I'm going to close it for the time being. Please feel free to re-open this PR whenever you wish to continue your work.

**Pull request closed without merging**
