### PR TITLE
Updated help link, embedded player per site

### PR DESCRIPTION
**Pull request by clash99**
### Proposed changes in this pull request

- Updated info link and changed to "help" 
- JS with embedded player switch based on site (let me know if there is a better way to do this)

### When should this PR be merged

- When possible - in Sprint 9

### Risks

- None foreseen

### Follow up actions

- Different topics are available per site as controlled by inlinemanual.  All help topics are available on staging and local although they don't all work properly there.  Need to test correct ones are being shown on demo and platform.

### CODE REVIEW

**Comment by clash99** [comment]
Completes #722

**Comment by ian-ross** [comment]
I'm not keen on the switch on `request.host` in `inline-manual-player.js`: presumably the random keys there are things that shouldn't be checked into a public source code repository?  It would be better to store the key in an environment variable and pick them up through the Django settings.  @amplifi I guess the way to do this would be to add an extra entry to the deployment JSON files, and have it picked up by the deployment scripts and passed through to Ansible.  Ansible can write it into `/etc/environment` and the `uwsgi.ini` (as for the other configuration stuff we need) and the Django settings can pick the thing up and give it a name for use in templates.  It all seems a bit complicated, but it's the right way to deal with these kinds of keys, I think.  Any thoughts on that?

**Comment by clash99** [comment]
@ian-ross:  That plan sounds logical.  I haven't done this before so let me look into it and dm you.

**Comment by ian-ross** [comment]
It's something that Adrienne or I would do.  It's probably not something you should touch, since it involves Django + Ansible + sysadmin things + custom Python deployment scripts that I wrote.  I'll talk to @amplifi about it.

**Comment by clash99** [comment]
@ian-ross got it - let me know if there is anything I can do to assist

**Comment by clash99** [comment]
I'm going to close this pull request to avoid confusion. Thanks @ian-ross and @amplifi for your assistance.

**Pull request closed without merging**
