### PR TITLE
Update some dependencies flagged by Requires.io (IV)

### LINKED ISSUE #1780: Broken browsable API for any filterable view
It appears that we are missing the template to render the Filter widget for our DRF browsable API views.

Errors:

* https://opbeat.com/cadasta/platform-staging/errors/213/
* https://opbeat.com/cadasta/platform-staging/errors/214/

**Note**: This only occurs on our rendered HTML views of our API. JSON responses still function as expected.

### Steps to reproduce the error

Navigate to any browsable API view that has filtering enabled.  e.g.:

* https://platform-staging.cadasta.org/api/v1/organizations/anthonys-qa19-test-org1/projects/
* https://platform-staging.cadasta.org/api/v1/organizations/anthonys-qa19-test-org1/projects/qa19-project/resources/

### Actual behavior

500 Error returned.

### Expected behavior

Rendered API view.

### PR DESCRIPTION
**Pull request by seav**
### Proposed changes in this pull request
Update some more dependencies and packages flagged by Requires.io. No platform code needs to be updated for this batch of updates.

### When should this PR be merged
Probably with Sprint 21 release.

### Risks
While the Travis build passes, and some very limited testing was done in the dev VM, extensive QA testing should be done (as part of QA day testing) to confirm there are no side-effects.

### Follow-up actions
Continue investigating/testing updated packages flagged by Requires.io.

#### General

- **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
  - [ ] Review 1
  - [ ] Review 2
- **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.
  - [ ] Review 1
  - [ ] Review 2

#### Functionality

- **Are all requirements met?** Compare implemented functionality with the requirements specification.
  - [ ] Review 1
  - [ ] Review 2
- **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 
  - [ ] Review 1
  - [ ] Review 2

#### Code

- **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
  - [ ] Review 1
  - [ ] Review 2
- **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
  - [ ] Review 1
  - [ ] Review 2
- **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 
  - [ ] Review 1
  - [ ] Review 2
- **Is the code documented sufficiently?** Large and complex classes, functions or methods must be annotated with comments following our [code-style guidelines](https://devwiki.corp.cadasta.org/Contributing%20Style%20Guide#documentation-and-comments).
  - [ ] Review 1
  - [ ] Review 2
- **Has the scalability of this change been evaluated?**
  - [ ] Review 1
  - [ ] Review 2
- **Is there a maintenance plan in place?**
  - [ ] Review 1
  - [ ] Review 2

#### Tests

- **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
  - [ ] Review 1
  - [ ] Review 2
- **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
  - [ ] Review 1
  - [ ] Review 2
- **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?
  - [ ] Review 1
  - [ ] Review 2

#### Security

- **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
  - [ ] Review 1
  - [ ] Review 2
- **Are all UI and API inputs run through forms or serializers?** 
  - [ ] Review 1
  - [ ] Review 2
- **Are all external inputs validated and sanitized appropriately?**
  - [ ] Review 1
  - [ ] Review 2
- **Does all branching logic have a default case?**
  - [ ] Review 1
  - [ ] Review 2
- **Does this solution handle outliers and edge cases gracefully?**
  - [ ] Review 1
  - [ ] Review 2
- **Are all external communications secured and restricted to SSL?**
  - [ ] Review 1
  - [ ] Review 2

#### Documentation

- **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
  - [ ] Review 1
  - [ ] Review 2
- **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki. 
  - [ ] Review 1
  - [ ] Review 2

### CODE REVIEW

**Comment by oliverroick** [comment]
- Moving this to high priority because it contains a security update for Django?
- @alukach can you please verify that adding `django_filters` to the settings fixes #1780?

**Comment by seav** [comment]
> Moving this to high priority because it contains a security update for Django?

According to the [release notes](https://github.com/django/django/blob/master/docs/releases/1.10.8.txt) this is indeed a security update, but we are probably not affected because it only affects sites where `DEBUG = True`, and we don't use that setting on production sites.

**Comment by seav** [comment]
Hmmm. This is weird. The push-commit and PR have passed on Travis but it seems GitHub is not picking up on the statuses.

**Comment by seav** [comment]
That makes sense. OK, I've created a separate PR #1787 for the #1780 bugfix.

**Comment by amplifi** [comment]
👍 Thanks!

**Pull request merged**
