### PR TITLE
Fix #946: Make usernames case insensitive

### LINKED ISSUE #946: Make usernames case insensitive
Usernames are currently case sensitive, allowing the existence of both "username" and "USERNAME". The platform should parse usernames as case insensitive to disallow this occurrence.

### PR DESCRIPTION
**Pull request by bjohare**
#### Fixes #946: Make usernames case insensitive

Currently, usernames are case sensitive. This PR makes username comparisons for account registration and profile updates case insensitive for both default and api views. New usernames and updates to existing usernames are checked for uniqueness against the full set of usernames using the `casefold` algorithm. Existing mixed-case usernames in the database remain untouched. 

- Add username comparisons using `casefold` to `RegisterForm` and `ProfileForm`.

- Add username comparisons using `casefold` to `RegistrationSerializer` and `UserSerializer`. 

- Added tests for the above changes.

### When should this PR be merged

Anytime.

### Risks

Low.

### Follow up actions

None required.

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ ] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by valaparthvi** [comment]
hey @bjohare , I have already been working on this. Here's my [PR](https://github.com/Cadasta/cadasta-platform/pull/1149)

**Comment by bjohare** [comment]
@valaparthvi, these are two different issues.. your PR fixes #1105 whereas this PR is a fix for #946

**Comment by valaparthvi** [comment]
hey @bjohare , yes I observed that. I just got too excited and commented. sorry for that.

**Comment by bjohare** [comment]
@valaparthivi, no problem :-)

**Comment by wonderchook** [comment]
@amplifi thoughts on how to handle the existing usernames that aren't case sensitive unique? I think we should probably do this manually and contact people. What are you thoughts?

**Comment by amplifi** [comment]
@wonderchook As of just now, all usernames in staging, demo, and prod are case-insensitive unique. There was one test account in staging, plus the production account (taken care of back in Nov by contacting the user) that prompted the original issue to require CI-uniqueness. I'll add a note to double-check and confirm that still holds before this PR goes live.

**Comment by bjohare** [comment]
@oliverroick fair point. I'll take a look.

**Pull request merged**
