### PR TITLE
Feature/#1164 sitelabel

### LINKED ISSUE #1164: Include a "Demo" label to make users more clear that they are in demo site
Currently there is no way for the users to distinguish whether they are in demo or in platform site. We should include a "Demo" notice in demo.cadasta.org site to make this more clear. 

@clash99 was already working on a proposal (thanks!).

### PR DESCRIPTION
**Pull request by clash99**
### Proposed changes in this pull request

- Fixes #1164 
- Branch based upon **feature/project-dashboard** branch with new header changes. Only last commit is new for this feature. (Is there a better way to do this PR?)
- Adds label following logo to designate platform, demo, staging or local

### When should this PR be merged

- When convenient

### Risks

- Low

### Follow-up actions

- None

#### General

- [x] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [x] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [x] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [x] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [x] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [x] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [x] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [x] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [x] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [x] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [x] **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [x] **Are all UI and API inputs run through forms or serializers?** 
- [x] **Are all external inputs validated and sanitized appropriately?**
- [x] **Does all branching logic have a default case?**
- [x] **Does this solution handle outliers and edge cases gracefully?**
- [x] **Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [x] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [x] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by seav** [comment]
@clash99: Is this PR also intended to merge the project dashboard changes as well? If not, I would prefer that we separate the site label changes from the project dashboard as a completely independent commit instead of branching it off from the **feature/project-dashboard** branch. Otherwise, I think it would be better to approve and then merge PR #1537 first before merging this PR.

**Comment by amplifi** [comment]
@seav PR #1537 has been merged

**Comment by seav** [comment]
Some further comments. The site label can't be localized so it will always be in English. I think this should be okay, but just letting everyone know.

Also, should this site label be mentioned somehow, somewhere in our documentation (paging @bethschechter and @dpalomino)? If so, then we should create a GitHub issue at the cadasta-docs repo to track this.

**Comment by amplifi** [comment]
Added https://github.com/Cadasta/cadasta-docs/issues/60 to reflect site label in documentation.

**Comment by dpalomino** [comment]
> Some further comments. The site label can't be localized so it will always be in English. I think this should be okay, but just letting everyone know.

Thanks @seav for the heads-up. Yes, I agree, I think this is okay.

**Pull request merged**
