### PR TITLE
Updated information link

### PR DESCRIPTION
**Pull request by clash99**
### Proposed changes in this pull request

- Updated link from info icon in header to use direct link to open help panel (vs id through inlinemanual which doesn't seem to be working)

### When should this PR be merged

-When convenient

### Risks

- None

### Follow up actions

- None

-----------------------------------------------------------------

Href for inline player in hamburger

### CODE REVIEW

**Comment by oliverroick** [comment]
The help panel opens as expected. There one issue though: The _sample project walkthrough_ links to a project, which only exists on the demo site but not on production. How is that handled then. Will the link be hidden on production?

**Comment by oliverroick** [comment]
^^^^^^
@clash99 Any comment on this?

**Comment by clash99** [comment]
no comment :|

I've checked in with inline manual and I believe I can limit it by site but would love to test more on staging.  If not, I will need to embed a different player for each site.

**Comment by oliverroick** [comment]
How should we proceed with this? I think, this shouldn't be merged before this is sorted.

**Comment by clash99** [comment]
I think if we can push to staging for testing it would be good.

**Comment by wonderchook** [comment]
@clash99 so the idea would be to push the branch to staging for testing first? @amplifi is this difficult to do (should we have a 2nd staging environment available for this or just use the current one?)

**Comment by amplifi** [comment]
@wonderchook @clash99 We can deploy this branch to staging for isolated testing, if that'll help. I'd recommend merging in master before we do.

**Comment by clash99** [comment]
Agree - lets get it to staging and then we can make sure its acting as expected.  If not, I will have to proceed with adding a different player per site.

**Comment by ian-ross** [comment]
@clash99 I saw that @amplifi deployed it to staging for testing, and I just had a quick look, but the "sample project walkthrough" option opens up a dialogue where the "Next" button takes me to a broken link.  In addition, it seems to set some cookie in my browser that makes it try to redirect to that link when I then try to reload platform-staging.cadasta.org...

**Pull request closed without merging**
